# DM_SIDM=2
# OPENMP=4
PMGRID=64 # was 512 # lr=512, hr=1024
MULTIPLEDOMAINS=4 # was 16 # lr=32, hr=16
# ADAPTIVE_GRAVSOFT_FORGAS
# HYDRO_MESHLESS_FINITE_MASS
# FIRE_PHYSICS_DEFAULTS
# BOX_PERIODIC
USE_FFTW3
HAVE_HDF5
#COOLING
#INPUT_POSITIONS_IN_DOUBLE
INPUT_IN_DOUBLEPRECISION
#OUTPUT_ADDITIONAL_RUNINFO
EVALPOTENTIAL
OUTPUT_POTENTIAL
OUTPUT_ACCELERATION
OUTPUT_POSITIONS_IN_DOUBLE
# LONGIDS
#EOS_GAMMA=(5.0/3.0)
# ALLOW_IMBALANCED_GASPARTICLELOAD
# PM_PLACEHIGHRESREGION=1+2+16
# PM_HIRES_REGION_CLIPPING=2000
# ADAPTIVE_GRAVSOFT_FORALL=2
GRAVITY_ANALYTIC #triaxial potential
#
