#define PMGRID 64
#define MULTIPLEDOMAINS 4
#define USE_FFTW3 
#define HAVE_HDF5 
#define INPUT_IN_DOUBLEPRECISION 
#define EVALPOTENTIAL 
#define OUTPUT_POTENTIAL 
#define OUTPUT_ACCELERATION 
#define OUTPUT_POSITIONS_IN_DOUBLE 
#define GRAVITY_ANALYTIC 
